language: cpp

clang-linux: &clang-linux
  os: linux
  dist: bionic
  python: "3.7"
  compiler: clang
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-bionic-8
      packages:
        - clang-8
        - libstdc++-8-dev
        - python3-pip

emscripten: &emscripten
  os: linux
  dist: bionic
  python: "3.7"
  compiler: clang
  addons:
    apt:
      packages:
        - python3-pip

osx: &osx
   os: osx
   language: generic
   osx_image: xcode11.3

install:
  - git clone https://github.com/TimSimpson/ci-land.git ci
  - pushd ci && git checkout 0d0994ed9803d74a6bc0bc161e34f2d63f6c6230 && popd
  - ./ci/cpp/conan/travis/install.sh

script:
  - ./ci/cpp/conan/travis/run.sh

matrix:
  include:

    - name: "Linux Clang 8.0 Release"
      <<: *clang-linux
      env:
        - PROFILE=clang-8-r-static
    - name: "Linux Clang 8.0 Debug"
      <<: *clang-linux
      env:
        - PROFILE=clang-8-d-static
env:
  global:
    - CIL_RUN_CALL_SOURCE=true
    - CONAN_LOGIN_USERNAME=TimSimpson
    - secure: "THFO4PEQCEnvMdph5amtlWSOB1d77xsq5vXQFKMNdQvN0PulyVetlSIwB72NnVIljgNfhi4fNKNTHttXQ5F85ecOhqur5YdR8+1jTc4Epo8VCOwVmMGhwJay8mrS9VZmtqY1Q5nX21ZjCPgX+rq0sIp0/M1sJUKm3K7bxeDtQT23wFaQiY8aiJD4epnaI1J08yiqctvH3vE/bQY/C1IWPmiBnT4SIJTxv/mwPPnK2k0X0OW9fK2mLCpmCEbE5SmyqBtJyuQySynQEpzXmClrCr/bqPg3Pp/N3DFK8fYMBq37RlxnDv3Lrv88RpcpEBcvpAorOjHf5FJlX6+hPVKr2XvCfbGqYBwLhex0GymVSOqeXdxJoYTtGRGWkhKUbj9sefrh2hhkJmNBd9LTTFZ2FZq2hdFgoXVGgXxYJE+P1DW7ep/+JOwwrEtDAkowBVOYOd3HkZZzE1BY51MH8nmLHwfjDSFW44SGILr4iAmnd4gzBtaamiMXHCyr3r2LetCv+4jqsq6TgBe1phvC/C4Akjl4YsG6yErURzbyMCWR9G8ltAZW2HXaqLOVGcNf39Q2Wn0eoR6W7jLrjBUCH+XpR7l7ElqiK7NbH5z3vukls8Zem9UTIoRUPJWO76EOSDmM1PWCQbSPiilnAEqO71zcWL5798aFhWVXsyhNuTwjSd8="