os: Visual Studio 2019

environment:
    PYTHON: "C:\Python37"

    matrix:


install:
  - git clone https://github.com/TimSimpson/ci-land.git ci
  - cd ci
  - git checkout 0d0994ed9803d74a6bc0bc161e34f2d63f6c6230
  - cd ..
  - ci\cpp\conan\appveyor\install.bat

build_script:
  - ci\cpp\conan\appveyor\run.bat %PROFILE%
